/*Pedidos especiais*/
$(document).ready(function(){
	$(".lado").hover(function(){
		$("#textprom").slideToggle("slow");
	});
});

/*ver+*/
$(document).ready(function(){
    $(".ver[data-person='#pepsi_lata']").click(function(){
      $("#div1").fadeIn();
    });
    $(".ver[data-person='#gua_lata']").click(function(){
        $("#div2").fadeIn();
    });
    $(".ver[data-person='#sum_lata']").click(function(){
        $("#div3").fadeIn();
    });
    $(".ver[data-person='#up_lata']").click(function(){
        $("#div4").fadeIn();
    });
    $(".ver[data-person='#pepsi_gar']").click(function(){
        $("#div5").fadeIn();
    });
    $(".ver[data-person='#gua_gar']").click(function(){
        $("#div6").fadeIn();
    });
    $(".ver[data-person='#up_gar']").click(function(){
        $("#div7").fadeIn();
    });
    $(".ver[data-person='#sum_gar']").click(function(){
        $("#div8").fadeIn();
    });
    $(".ver[data-person='#pizzas_tres']").click(function(){
        $("#div9").fadeIn();
    });
    $(".ver[data-person='#pizzas_dois']").click(function(){
        $("#div10").fadeIn();
    });
    $(".ver[data-person='#pizzas_trinta']").click(function(){
        $("#div11").fadeIn();
    });
    $(".ver[data-person='#refri']").click(function(){
        $("#div12").fadeIn();
    });
    $(".ver[data-person='#king']").click(function(){
        $("#div13").fadeIn();
    });
    $(".ver[data-person='#familia']").click(function(){
        $("#div14").fadeIn();
    });
    $(".ver[data-person='#paradois']").click(function(){
        $("#div15").fadeIn();
    });
    $(".ver[data-person='#individual']").click(function(){
        $("#div16").fadeIn();
    });
    $(".ver[data-person='#qua_queijo']").click(function(){
        $("#div17").fadeIn();
    });
    $(".ver[data-person='#peperoni']").click(function(){
        $("#div18").fadeIn();
    });
    $(".ver[data-person='#kebab']").click(function(){
        $("#div19").fadeIn();
    });
    $(".ver[data-person='#camarao']").click(function(){
        $("#div20").fadeIn();
    });
    $(".ver[data-person='#veg_ananas']").click(function(){
        $("#div21").fadeIn();
    });
    $(".ver[data-person='#veg_rustica']").click(function(){
        $("#div22").fadeIn();
    });
    $(".ver[data-person='#pi_bacon']").click(function(){
        $("#div23").fadeIn();
    });
    $(".ver[data-person='#pi_frango']").click(function(){
        $("#div24").fadeIn();
    });
    $(".ver[data-person='#alho_sim']").click(function(){
        $("#div25").fadeIn();
    });
    $(".ver[data-person='#alho_bacon']").click(function(){
        $("#div26").fadeIn();
    });
    $(".ver[data-person='#natad']").click(function(){
        $("#div27").fadeIn();
    });
    $(".ver[data-person='#natau']").click(function(){
        $("#div28").fadeIn();
    });
    $(".ver[data-person='#choc']").click(function(){
        $("#div29").fadeIn();
    });
    $(".ver[data-person='#mara']").click(function(){
        $("#div30").fadeIn();
    });
    $(".ver[data-person='#clas']").click(function(){
        $("#div31").fadeIn();
    });
    $(".ver[data-person='#bra']").click(function(){
        $("#div32").fadeIn();
    });
});
  $(document).ready(function(){
    $("#fechar[data-person='#pepsi_lata']").click(function(){
      $("#div1").fadeOut();
    });
    $("#fechar[data-person='#gua_lata']").click(function(){
        $("#div2").fadeOut();
      });
      $("#fechar[data-person='#sum_lata']").click(function(){
        $("#div3").fadeOut();
    });
    $("#fechar[data-person='#up_lata']").click(function(){
        $("#div4").fadeOut();
    });
    $("#fechar[data-person='#pepsi_gar']").click(function(){
        $("#div5").fadeOut();
    });
    $("#fechar[data-person='#gua_gar']").click(function(){
        $("#div6").fadeOut();
    });
    $("#fechar[data-person='#up_gar']").click(function(){
        $("#div7").fadeOut();
    });
    $("#fechar[data-person='#sum_gar']").click(function(){
        $("#div8").fadeOut();
    });
    $("#fechar[data-person='#pizzas_tres']").click(function(){
        $("#div9").fadeOut();
    });
    $("#fechar[data-person='#pizzas_dois']").click(function(){
        $("#div10").fadeOut();
    });
    $("#fechar[data-person='#pizzas_trinta']").click(function(){
        $("#div11").fadeOut();
    });
    $("#fechar[data-person='#refri']").click(function(){
        $("#div12").fadeOut();
    });
    $("#fechar[data-person='#king']").click(function(){
        $("#div13").fadeOut();
    });
    $("#fechar[data-person='#familia']").click(function(){
        $("#div14").fadeOut();
    });
    $("#fechar[data-person='#paradois']").click(function(){
        $("#div15").fadeOut();
    });
    $("#fechar[data-person='#individual']").click(function(){
        $("#div16").fadeOut();
    });
    $("#fechar[data-person='#qua_queijo']").click(function(){
        $("#div17").fadeOut();
    });
    $("#fechar[data-person='#peperoni']").click(function(){
        $("#div18").fadeOut();
    });
    $("#fechar[data-person='#kebab']").click(function(){
        $("#div19").fadeOut();
    });
    $("#fechar[data-person='#camarao']").click(function(){
        $("#div20").fadeOut();
    });
    $("#fechar[data-person='#veg_ananas']").click(function(){
        $("#div21").fadeOut();
    });
    $("#fechar[data-person='#veg_rustica']").click(function(){
        $("#div22").fadeOut();
    });
    $("#fechar[data-person='#pi_bacon']").click(function(){
        $("#div23").fadeOut();
    });
    $("#fechar[data-person='#pi_frango']").click(function(){
        $("#div24").fadeOut();
    });
    $("#fechar[data-person='#alho_simp']").click(function(){
        $("#div25").fadeOut();
    });
    $("#fechar[data-person='#alho_bacon']").click(function(){
        $("#div26").fadeOut();
    });
    $("#fechar[data-person='#natad']").click(function(){
        $("#div27").fadeOut();
    });
    $("#fechar[data-person='#natau']").click(function(){
        $("#div28").fadeOut();
    });
    $("#fechar[data-person='#choc']").click(function(){
        $("#div29").fadeOut();
    });
    $("#fechar[data-person='#mara']").click(function(){
        $("#div30").fadeOut();
    });
    $("#fechar[data-person='#clas']").click(function(){
        $("#div31").fadeOut();
    });
    $("#fechar[data-person='#bra']").click(function(){
        $("#div32").fadeOut();
    });
  });  

 

 


